<?php

namespace AppBundle\Repository;

/**
 * KuenstlerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KuenstlerRepository extends \Doctrine\ORM\EntityRepository
{
}
