<?php

namespace AppBundle\Repository;

/**
 * LiedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiedRepository extends \Doctrine\ORM\EntityRepository
{
}
